apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: redis-ip-pool
  namespace: metallb-system
spec:
  addresses:
    - 172.24.255.200-172.24.255.210   # adjust to your local network range
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: redis-l2
  namespace: metallb-system


# kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.10/config/manifests/metallb-native.yaml
