apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        service: redis
    spec:
      nodeSelector:
        region: ca-south
      volumes:
        - name: acl-volume
          configMap:
            name: redis-acl-config
            items:
              - key: users.acl
                path: users.acl
      containers:
        - name: redis
          image: redis:6.2-alpine
          args: ["redis-server", "--aclfile", "/etc/redis/users.acl"]
          volumeMounts:
            - name: acl-volume
              mountPath: /etc/redis/users.acl
              subPath: users.acl
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "100Mi"
              cpu: "300m"
          ports:
            - containerPort: 6379

      
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    service: redis
  ports:
    - protocol: TCP
      port: 6379        # Service port
      targetPort: 6379  # Container port
  type: LoadBalancer     # Internal service (default)


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-acl-config
data:
  users.acl: |
    user default off
    user admin on >admin allcommands allkeys
